### CREATE five documents.
POST http://localhost:3000/jobs HTTP/1.1
content-type: application/json

{
    "company": "WalMart",
    "title": "Greeter",
    "years": 10,
    "date": "2011-03-11"
}


### CREATE 2
POST http://localhost:3000/jobs HTTP/1.1
content-type: application/json

{
    "company": "Verizon",
    "title": "Sales Specialist",
    "years": 5,
    "date": "2015-05-22"
}

### CREATE 3
POST http://localhost:3000/jobs HTTP/1.1
content-type: application/json

{
    "company": "Blockbuster",
    "title": "Manager",
    "years": 10,
    "date": "1994-02-17"
}

### CREATE 4
POST http://localhost:3000/jobs HTTP/1.1
content-type: application/json

{
    "company": "Discover",
    "title": "Customer Service Representative",
    "years": 7,
    "date": "2010-07-21"
}

### CREATE 5
POST http://localhost:3000/jobs HTTP/1.1
content-type: application/json

{
    "company": "Pepsi",
    "title": "Assistant Manager",
    "years": 11,
    "date": "2006-11-05"
}


### RETRIEVE all documents.
GET http://localhost:3000/jobs HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/jobs/64dea0a2cdfb29032b18211e HTTP/1.1


### UPDATE one document's year, by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/jobs/64dea0a2cdfb29032b18211e HTTP/1.1
content-type: application/json

{
    "company": "Google",
    "title": "Software Engineer",
    "years": 1,
    "date": "2022-05-20"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/jobs/64dea0f04e2467fb8f277349 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/jobs HTTP/1.1

